name: cheerful_rob
services:
  main_app:
    cpu_shares: 10
    command: []
    container_name: mm
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      - MM_CUSTOMCSS_FILE=css/custom.css
      - MM_MODULES_DIR=modules
      - MM_OVERRIDE_CSS=true
      - MM_OVERRIDE_DEFAULT_MODULES=true
      - MM_SCENARIO=server
      - MM_SHOW_CURSOR=true
    hostname: mm
    image: karsten13/magicmirror:latest
    labels:
      icon: https://img.icons8.com/?size=50&id=64406&format=png
    ports:
      - target: 8080
        published: "8080"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/mm/config
        target: /opt/magic_mirror/config
      - type: bind
        source: /DATA/mm/modules
        target: /opt/magic_mirror/modules
      - type: bind
        source: /DATA/mm/css
        target: /opt/magic_mirror/css
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://img.icons8.com/?size=50&id=64406&format=png
  index: /
  is_uncontrolled: false
  port_map: "8080"
  scheme: http
  store_app_id: cheerful_rob
  title:
    custom: Magic Mirror
